import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import './editor.css';
import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} font-inter antialiased`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
