import { ApolloWrapper } from '@/lib/apollo-client';
import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import './editor.css';
import './globals.css';
import AuthWrapper from '@/components/AuthWrapper';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// eslint-disable-next-line no-undef
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} font-inter antialiased`}
      >
        <ApolloWrapper>
          <AuthWrapper>{children}</AuthWrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
